language: node_js
node_js: 12
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run is-es5
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run coveralls
env:
  global:
    - secure: UFXypEVAwfTGlh5uP8uGc9hfSBvMpiJ+L4MgBi6Bou/sti/jrKoCe3ZOvO3LZVxlJuHdd5+wUuZbBp6MdUClcs9qNdmVAhl0YdhzThoioIihtEE9eHRI+a736CRKgCO+LYZ349GXE9DTBsU6nH8GgHopubFqA3P5CtZhgs1DwP96QgPLioRqkHkjH1brJUjoJ1p9bhiGxk1IlQBKXzKnR0OhCql5c14H/p39p711/YXKa1Hr9z+1rvtLYoQ3AblGJUWLbWlSMmyJzXtjdV2Xngr8ZX8xMp5bXGAVTzHBueDnMvqhmV9VUHMr1d96LS34vmU03a3/GGbB/hqI61Rcxr93tjv+UqhizorUd0wrWpuPViF7Fh8sX14/Z1+jbxzUgQjFoHSi8Q4/pyhBgo9F4KVxkXWFUckh2lRyZHvZYBKX/9j5kzg9qVIcMM7gDY7x8RO0GIC6Re+SLMsyV5fRhMTvWablkZPMFx9zqolq5aunbNcoItmxIyciMAqizSQGlbt5djeL2A4KLdHQu3LGeHtzD4p4I705A0DSQLbykwCC2XEYs/P7/BIemUDGDi6ZIvD/Jk6lveO63DcZ6bu13whvz1L7ltd8hwhOkkzOZHlszIl7Hu2IFeDm6ht3ioGvJ9GXnxi2XECM9kY0zOxlDr+NglhFtf83v9dOeyJlzcI=
    - secure: GsDPEnIBhS9SHSTtXDO6TOsrp+MpGAS8xHi+iOXwl/EQ35aWJugM9ZMtdJ50kOPJ2vJy2VpK6BiMc1pa0swztpTtzcRSbi8/2WPnVqdeGvh34EIS5uFqmcw4bIAiLh0kcTjtZtwK2wfEF2MpSpVWxj6AplJECEyCeUb4QNc0MDVCcW29q1WTCokkvoaZTuGQGjsSVeGrkWTDq6cR966/uHGg2D4OXTY6ucjEYNhQDgVhgRatevkrKd7gETsxkVNNCa1sFS4xz8mkz+pd+OeM1DqA2PcdZR3AwrAuv2hNTF128HPCZFWKhp+HB+Qxn6C50EjhcpfE/GE8a03zZ0Ge0ztqQYBFbFaaoLaSTpmDavW/IrE4hDXthBJAQoeYWCeOcDNKpGVadtceTXDYvX9wcGi1nEeR+4QemX2kbW27sRc0Je2COWw8moDhqlA/HClw+HnB8qq60dglsZ9oiA2ABFuKZLwUhPk4Kub0wITGpIqfZfJnsdweLIw3crcTP0ujIywTcYKPtmUGSddcAELA1/B9GMtcnC5+B5pznqb3g4VvfGmqWH04xb7dZ4DKZChZBaLAFG35yZDT7FaSE2lXpxmjvtLQdTkbShLmDEhhtF3OXwESj3C7zbOMlUxcMqe+b8R8+dcSiwBJjtxcns4EXiMIDkkXkdssmOQN0NCCSEo=
