name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # lerna expects to be authenticated for publishing to NPM. This step will fail CI if NPM is not
      # authenticated, even though this build does _not_ attempt to publish, as an extra check before merge
      # that Lerna is set to publish.
      - name: Check NPM authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}" >> .npmrc
          npm whoami
      - name: Install Dependencies
        run: npm ci
      - name: Lerna Bootstrap
        run: npm run bootstrap
      - name: Lint
        run: npm run ci:lint
      - name: Test
        run: npm run ci:test
      - name: Coverage Report
        uses: codecov/codecov-action@v1
      - name: Build
        run: npm run ci:build
      - name: Preview Changed Packages
        run: npm run changed
