name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # lerna expects to be authenticated for publishing to NPM. This step will fail CI if NPM is not authenticated
      - name: Check NPM authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}" >> .npmrc
          npm whoami
      - name: Install Dependencies
        run: npm ci
      - name: Run Lerna Bootstrap
        run: npm run bootstrap
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Coverage Report
        uses: codecov/codecov-action@v1
      - name: Build
        run: npm run build
      - name: Preview Changed Packages
        run: npm run changed
      - name: Publish Changed Packages
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
